import { Product, StoreSettings } from './types.js';

export const DEFAULT_STORE_SETTINGS: StoreSettings = {
  storeName: 'AKASH STORE',
  ownerName: 'Akash Chondror Roy',
  headquarters: 'Sherpur, Bogura, Bangladesh',
  contactEmail: 'akashchondroroy@protonmail.com',
  supportPhoneDisplay: 'Available via Support Agent',
  currency: 'BDT',
  currencySymbol: '৳',
  bkashNumber: '01874839665',
  bkashEnabled: true,
  nagadNumber: '',
  nagadEnabled: false,
  codEnabled: true,
  codRequiresConfirmation: true,
  insideDhakaFee: 60,
  outsideDhakaFee: 120,
  freeDeliveryThreshold: 2000,
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_001',
    name: 'Samsung Galaxy A55 5G (8GB/256GB)',
    slug: 'samsung-galaxy-a55-5g',
    sku: 'AKS-SAM-A55-01',
    category: 'Electronics',
    brand: 'Samsung',
    shortDescription: 'Super AMOLED 120Hz display, 50MP OIS camera, 5000mAh battery with official Bangladesh warranty.',
    description: 'The Samsung Galaxy A55 5G brings metal frame premium design, Knox Vault security, and IP67 dust/water resistance. Perfect for high-speed multitasking and mobile photography.',
    price: 46999,
    compareAtPrice: 49999,
    stock: 14,
    lowStockThreshold: 5,
    status: 'ACTIVE',
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80',
    ],
    variants: [
      { id: 'v_a55_awesome_iceblue', name: 'Awesome Iceblue / 8GB + 256GB', sku: 'AKS-SAM-A55-BLU', price: 46999, stock: 8, attributes: { color: 'Iceblue', storage: '256GB' } },
      { id: 'v_a55_awesome_navy', name: 'Awesome Navy / 8GB + 256GB', sku: 'AKS-SAM-A55-NVY', price: 46999, stock: 6, attributes: { color: 'Navy', storage: '256GB' } },
    ],
    specifications: {
      Display: '6.6" FHD+ Super AMOLED 120Hz',
      Processor: 'Exynos 1480 (4nm)',
      RearCamera: '50MP (OIS) + 12MP Ultra-Wide + 5MP Macro',
      FrontCamera: '32MP',
      Battery: '5000mAh (25W Fast Charging)',
      Warranty: '1 Year Official Warranty',
    },
    tags: ['smartphone', 'samsung', '5g', 'electronics'],
    rating: 4.8,
    reviewCount: 38,
    createdAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'prod_002',
    name: 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones',
    slug: 'sony-wh-1000xm5-headphones',
    sku: 'AKS-SNY-XM5-02',
    category: 'Gadgets',
    brand: 'Sony',
    shortDescription: 'Industry-leading noise cancellation with two processors and 8 microphones for unparalleled calls and music.',
    description: 'Engineered to perfection with Auto NC Optimizer, lightweight design with soft fit leather, and up to 30 hours of continuous battery life.',
    price: 36500,
    compareAtPrice: 38990,
    stock: 9,
    lowStockThreshold: 3,
    status: 'ACTIVE',
    images: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    ],
    variants: [
      { id: 'v_xm5_black', name: 'Matte Black', sku: 'AKS-SNY-XM5-BLK', price: 36500, stock: 5, attributes: { color: 'Black' } },
      { id: 'v_xm5_silver', name: 'Platinum Silver', sku: 'AKS-SNY-XM5-SLV', price: 36500, stock: 4, attributes: { color: 'Silver' } },
    ],
    specifications: {
      BatteryLife: 'Up to 30 Hours (NC On)',
      DriverUnit: '30mm Carbon Fiber',
      Microphones: '8 Microphones beamforming',
      Connectivity: 'Bluetooth 5.2, LDAC, Multipoint',
      Weight: '250g',
    },
    tags: ['headphones', 'audio', 'sony', 'wireless', 'gadgets'],
    rating: 4.9,
    reviewCount: 52,
    createdAt: '2026-02-18T14:00:00.000Z',
  },
  {
    id: 'prod_003',
    name: "Men's Premium Washed Cotton Slim Fit Casual Shirt",
    slug: 'mens-premium-washed-cotton-shirt',
    sku: 'AKS-FSH-SHIRT-03',
    category: 'Fashion',
    brand: 'Akash Heritage',
    shortDescription: '100% combed breathable cotton with tailored button-down collar and durable stitching.',
    description: 'Crafted from premium long-staple cotton for year-round comfort in Bangladesh climate. Pre-shrunk and enzyme washed for ultra-soft hand feel.',
    price: 1850,
    compareAtPrice: 2200,
    stock: 45,
    lowStockThreshold: 10,
    status: 'ACTIVE',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80',
    ],
    variants: [
      { id: 'v_shirt_olive_m', name: 'Olive Green / Medium', sku: 'AKS-SHIRT-OLV-M', price: 1850, stock: 12, attributes: { color: 'Olive', size: 'M' } },
      { id: 'v_shirt_olive_l', name: 'Olive Green / Large', sku: 'AKS-SHIRT-OLV-L', price: 1850, stock: 15, attributes: { color: 'Olive', size: 'L' } },
      { id: 'v_shirt_navy_m', name: 'Classic Navy / Medium', sku: 'AKS-SHIRT-NVY-M', price: 1850, stock: 10, attributes: { color: 'Navy', size: 'M' } },
      { id: 'v_shirt_navy_l', name: 'Classic Navy / Large', sku: 'AKS-SHIRT-NVY-L', price: 1850, stock: 8, attributes: { color: 'Navy', size: 'L' } },
    ],
    specifications: {
      Material: '100% Combed Cotton',
      Pattern: 'Solid Enzyme Washed',
      Collar: 'Spread Button-Down',
      Care: 'Machine Wash Cold, Hang Dry',
    },
    tags: ['fashion', 'men', 'shirt', 'clothing'],
    rating: 4.7,
    reviewCount: 26,
    createdAt: '2026-03-12T11:00:00.000Z',
  },
  {
    id: 'prod_004',
    name: 'Anker 737 Power Bank (PowerCore 24K, 140W)',
    slug: 'anker-737-power-bank-140w',
    sku: 'AKS-ANK-737-04',
    category: 'Gadgets',
    brand: 'Anker',
    shortDescription: 'Ultra-powerful 140W two-way fast charging with smart digital display and 24,000mAh capacity.',
    description: 'Charge your laptop, tablet, and smartphone simultaneously at lightning speed. Equipped with PowerIQ 4.0 technology and ActiveShield 2.0 real-time temperature protection.',
    price: 13500,
    compareAtPrice: 14990,
    stock: 18,
    lowStockThreshold: 4,
    status: 'ACTIVE',
    images: [
      'https://images.unsplash.com/photo-1609592424328-98e38d7c2a71?w=800&q=80',
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80',
    ],
    variants: [
      { id: 'v_anker737_default', name: 'Space Gray 24,000mAh', sku: 'AKS-ANK-737-GRY', price: 13500, stock: 18, attributes: { color: 'Space Gray' } },
    ],
    specifications: {
      Capacity: '24,000mAh',
      TotalOutput: '140W Max',
      Ports: '2x USB-C + 1x USB-A',
      Display: 'Smart Digital Color Display',
      Warranty: '18 Months Warranty',
    },
    tags: ['gadgets', 'powerbank', 'fast-charging', 'anker'],
    rating: 4.9,
    reviewCount: 41,
    createdAt: '2026-02-25T15:00:00.000Z',
  },
  {
    id: 'prod_005',
    name: 'Authentic Pure Sundarban Honey (500g Jar)',
    slug: 'sundarban-raw-wild-honey-500g',
    sku: 'AKS-GRO-HONEY-05',
    category: 'Grocery',
    brand: 'Bengal Pure',
    shortDescription: '100% natural unfiltered raw wild honey sustainably harvested from deep mangrove forests of Sundarban.',
    description: 'Raw, unpasteurized, and rich in natural enzymes, antioxidants, and trace minerals. Directly collected from local traditional Mouwals in the Sundarbans.',
    price: 850,
    compareAtPrice: 950,
    stock: 60,
    lowStockThreshold: 15,
    status: 'ACTIVE',
    images: [
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&q=80',
      'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80',
    ],
    variants: [
      { id: 'v_honey_500g', name: '500g Glass Jar', sku: 'AKS-HNY-500G', price: 850, stock: 35, attributes: { weight: '500g' } },
      { id: 'v_honey_1000g', name: '1kg Glass Jar', sku: 'AKS-HNY-1000G', price: 1600, stock: 25, attributes: { weight: '1kg' } },
    ],
    specifications: {
      Origin: 'Sundarban Mangrove Forest, Bangladesh',
      Type: 'Raw Multi-Flora Wild Honey',
      Packaging: 'Food-Grade Air Tight Glass Jar',
      ShelfLife: '24 Months',
    },
    tags: ['grocery', 'organic', 'honey', 'bangladesh'],
    rating: 4.9,
    reviewCount: 88,
    createdAt: '2026-01-15T09:00:00.000Z',
  },
  {
    id: 'prod_006',
    name: 'CeraVe Moisturizing Cream with Ceramides (454g)',
    slug: 'cerave-moisturizing-cream-454g',
    sku: 'AKS-BTY-CRV-06',
    category: 'Beauty',
    brand: 'CeraVe',
    shortDescription: 'Essential 3 ceramides and hyaluronic acid for barrier-restoring, 24-hour hydration.',
    description: 'Developed with dermatologists, this non-comedogenic, fragrance-free formula uses MVE Delivery Technology for continuous hydration on dry to very dry skin.',
    price: 2450,
    compareAtPrice: 2800,
    stock: 22,
    lowStockThreshold: 6,
    status: 'ACTIVE',
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
      'https://images.unsplash.com/photo-1608248597359-54859a85bc1f?w=800&q=80',
    ],
    variants: [
      { id: 'v_crv_454g', name: '454g Tub with Pump', sku: 'AKS-CRV-454G', price: 2450, stock: 22, attributes: { size: '454g' } },
    ],
    specifications: {
      SkinType: 'Dry to Very Dry Skin',
      KeyIngredients: 'Ceramides 1, 3, 6-II, Hyaluronic Acid',
      Formulation: 'Fragrance-Free Cream',
      CountryOfOrigin: 'USA',
    },
    tags: ['beauty', 'skincare', 'cerave', 'moisturizer'],
    rating: 4.8,
    reviewCount: 64,
    createdAt: '2026-02-10T13:00:00.000Z',
  },
];
